# Docker compose file for production

version: '3.9'

services:

  django:
    container_name: django
    restart: always
    build:
      context: ./time_tracker
      dockerfile: Dockerfile_prod
    volumes:
      - /var/log/gunicorn:/home/time_tracker/log
      - static:/home/time_tracker/static_root  # Named volume shared with the nginx container
    env_file:
      - ./env/prod.env  # This file should be built using GitHub secrets
    command:
      - bash
      - -c
      - |
        python3.10 manage.py migrate
        python3.10 manage.py collectstatic --no-input
        gunicorn -c gunicorn_conf.py time_tracker.wsgi

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile_prod
    volumes:
      - /var/log/nginx:/var/log/nginx
      - static:/static  # Named volume shared with the django container
      - ./certbot/www:/var/www/certbot/:ro  # Certbot webroot
      - ./certbot/conf/:/etc/letsencrypt/:ro  # Certbot certificates
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - django

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw  # Certbot webroot
      - ./certbot/conf/:/etc/letsencrypt/:rw  # Certbot certificates
    command:
      - certonly
      - --keep-until-expiring
      - --webroot
      - --webroot-path
      - /var/www/certbot
      - --agree-tos
      - --email
      - fxie@timetracker.club
      - --no-eff-email
      - -d
      - www.timetracker.club
      - -d
      - timetracker.club
    depends_on:
      - nginx

volumes:
  static:
