# Docker compose file for production

version: '3.9'

services:

  django:
    container_name: django
    image: fxie520/time_tracker:django
    volumes:
      - /var/log/gunicorn:/home/time_tracker/log
      - /home/time_tracker/venv
      - static:/home/time_tracker/static_root  # Named volume shared with the nginx container
    env_file:
      - ./env/prod.env  # This file is built using GitHub secrets
    command:
      - bash
      - -c
      - |
        python3.10 manage.py migrate
        python3.10 manage.py collectstatic --no-input
        python3.10 manage.py runserver 0.0.0.0:8000
#        gunicorn -c gunicorn_conf.py time_tracker.wsgi

  nginx:
    container_name: nginx
    image: fxie520/time_tracker:nginx
    volumes:
      - /var/log/nginx:/var/log/nginx
#      - /etc/letsencrypt/live/timetracker.club:/letsencrypt  # Bind mount: mount SSL certificate files in container
      - static:/static  # Named volume shared with the django container
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - django

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command:
      - certonly
      - --webroot
      - --webroot-path
      - /var/www/certbot
      - --email
      - fxie@timetracker.club
      - --agree-tos
      - --email EMAIL
      - --no-eff-email
      - -d
      - www.timetracker.club
      - -d
      - timetracker.club
    depends_on:
      - nginx

volumes:
  static:
